import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google"
import Navbar from "@/components/Navbar";
import Container from "@/components/Container";
import Footer from "@/components/Footer";

const poppins = Poppins({
    weight: ['400', '500', '600'],
    subsets: ["latin"],
    variable: "--font-poppins"
})




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.variable}  h-full antialiased`}
    >
      <body className="min-h-full bg-color text-white flex flex-col" >
        <Navbar />
        <Container>
        {children}
        </Container>
        <Footer />
        </body>
    </html>
  );
}
